#### Show databases

In [ ]:
sqoop list-databases
--connect "jdbc:mysql://hostname:port_no/database_name"
--username user_name
--password password

#### Show tables

In [ ]:
sqoop list-tables  
--connect "jdbc:mysql://hostname:port_no/database_name"
--username user_name
--password password

#### Run query with sqoop

In [ ]:
sqoop eval \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--query "select count(1) from tbl_name"

### Sqoop Import

#### Import all tables

In [ ]:
sqoop import-all-tables \
-m 12 \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--as-avrodatafile \
--warehouse-dir=/path/dir_name

#### Save as Text File and compressed

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table departments \
--as-textfile \
--target-dir=/path/dir_name \
--compress \
--compression-codec org.apache.hadoop.io.compress.SnappyCodec

#### Append

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table table_name \
--target-dir=/path/dir_name \
--append

#### Overwrite

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
--delete-target-dir

#### Save as Sequence File

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--as-sequencefile \
--target-dir=/path/dir_name

#### Save as Avro File

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--as-avrodatafile \
--target-dir=/path/dir_name

#### Save as Parquet File

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--as-parquetfile \
--target-dir=/path/dir_name

#### Delimiters and NULL string

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
--enclosed-by \" \
--fields-terminated-by \:
--lines-terminated-by \\n \
--null-string null \
--null-non-string null

#### Where and Cloumns arguments

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
--where "id > 5"
--columns id,name

#### Boundary Query and columns argument

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
-m 2 \
--boundary-query "select 2, 8 from table_name limit 1" \
--columns id,name

#### Query argument

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
-m 2 \
--query "select name from tbl_name where name = "value" and \$CONDITIONS" \
--split-by id

#### Incremental Load

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--target-dir=/path/dir_name
--fields-terminated-by '|' \
--lines-terminated-by '\n' \
--check-column "id" \
--incremental append \
--last-value 70 \
--outdir java_files

#### Hive Import

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--fields-terminated-by '|' \
--lines-terminated-by '\n' \
--hive-home /path/dir_name \
--hive-import \
--hive-overwrite \
--hive-database hive_database_name \
--hive-table tbl_name \

### Sqoop Export

#### Updating and inserting

In [ ]:
sqoop export 
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--export-dir /path/dir_name \
--num-mappers 4 \
--update-key id \
--update-mode allowinsert

#### Delimiters and NULL string (Exporting data from Hive)

In [ ]:
sqoop export \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table tbl_name \
--export-dir /path/dir_name \
--input-fields-terminated-by '\001' \
--input-lines-terminated-by '\n' \
--num-mappers 2 \
--input-null-string null \
--input-null-non-string -1

### Sooop Merge

##### All below steps are part of one merge process
##### This example shows when database is updated or new rows are inserted how to merge the new import with previous imported data

#### Make dir for merge process

In [ ]:
hadoop fs -mkdir /path/sqoop_merge

#### Initial load

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table table_name \
--target-dir=/path/sqoop_merge/initial_file

#### Validate records

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--query "select * from tbl_name" 

# Verify the results
hadoop fs -cat /path/sqoop_merge/initial_file/part*

#### Update record

In [ ]:
sqoop eval 
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--query "update tbl_name set name='value' where id = 70"

#### Insert

In [ ]:
sqoop eval 
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--query "insert into tbl_name values (80, 'New Record')"

#### Validate

In [ ]:
sqoop eval 
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--query "select * from tbl_name"

#### New load

In [ ]:
sqoop import \
--connect "jdbc:mysql://hostname:port_no/database_name" \
--username user_name \
--password password \
--table table_name \
--target-dir=/path/sqoop_merge/updated_file \
--where "id >= 70"

# Verify the results
hadoop fs -cat /path/sqoop_merge/updated_file/part*

#### Merge

In [ ]:
sqoop merge 
--merge-key id \
--new-data /path/sqoop_merge/updated_file \
--onto path/sqoop_merge/initial_file \
--target-dir /path/sqoop_merge/staging_dir \
--class-name tbl_name \
--jar-file jar_file	

# Verify the results
hadoop fs -cat /path/sqoop_merge/staging_dir/part*

#### Move/Rename stage directory to original directory

In [ ]:
hadoop fs -mv /path/sqoop_merge/staging_dir /path/sqoop_merge/final_file

#### Validate Merge

In [ ]:
hadoop fs -cat /path/sqoop_merge/final_file/part*

#### Remove old directory

In [ ]:
hadoop fs -rm -R /path/sqoop_merge/initial_file /path/sqoop_merge/staging_dir